name: sam_assistant
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  audio_waveforms: ^1.0.4
  contained_tab_bar_view: ^0.8.0
  cupertino_icons: ^1.0.2
  dartx: ^1.1.0
  dartz: ^0.10.1
  dropdown_button2: ^2.0.0
  dropdown_search: ^5.0.6
  easy_localization: ^3.0.1
  ellipsized_text: ^1.0.2
  expandable: ^5.0.1
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_highlight: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_math_fork: ^0.6.3+1
  flutter_smart_dialog: ^4.9.0+4
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.4
  flutter_uix: ^0.1.2-nullsafety.2
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  go_router: ^6.5.1
  google_fonts: ^4.0.3
  grpc: ^3.1.0
  hooks_riverpod: ^2.3.2
  html: ^0.15.3
  http2: ^2.0.0
  image: ^4.0.15
  image_picker: ^0.8.7+4
  interactive_bottom_sheet: ^0.1.2
  json_serializable: ^6.6.1
  just_the_tooltip: ^0.0.12
  logger: ^1.3.0
  markdown: ^7.1.0
  markdown_widget: ^2.1.0
  objectbox: ^2.0.0
  objectbox_sync_flutter_libs: any
  protobuf: ^2.0.0
  quickalert: ^1.0.1
  responsive_builder: ^0.6.4
  rive: ^0.10.3
  rive_splash_screen: ^0.1.1
  sentry_flutter: ^7.5.1
  timeago: ^3.0.0
  video_player: ^2.6.1
  widgetbook: ^3.0.0-beta.13

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  objectbox_generator: ^2.0.0
  riverpod_generator: ^2.1.4
  riverpod_lint: null

dependency_overrides:
  flutter_svg: ^2.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/icons/
    - assets/rive/
    - .env
